### ISSUE TITLE
New Build seems to be broken?

### ISSUE THREAD

**Issue by JeremyRubin** [borisdayma/dalle-mini#113]
seeing:

ImportError: attempted relative import with no known parent package
Traceback:
File "/home/user/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/home/user/app/app/streamlit/app.py", line 6, in <module>
    from .backend import ServiceError, get_images_from_backend

on the webapp at https://huggingface.co/spaces/flax-community/dalle-mini

p.s. i love this project and use it to make art

**Comment by borisdayma** [comment]
Thanks for letting me know. This should now be fixed.

**Comment by lucialam172** [comment]
very interesting topic
[https://github.com/lucialam172/dark-kitchen-cabinets](https://github.com/lucialam172/dark-kitchen-cabinets)
[https://github.com/lucialam172](https://github.com/lucialam172)
[https://lucialam172.github.io/dark-kitchen-cabinets](https://lucialam172.github.io/dark-kitchen-cabinets)
