### ISSUE TITLE
separate optimizer artifact from model artifact

### ISSUE THREAD

**Issue by borisdayma** [borisdayma/dalle-mini#120]
This will let us download and cache artifacts faster when the optimizer is not needed

**Comment by borisdayma** [comment]
One issue is the convenient `resume_from_checkpoint` would then need 2 artifacts (model + optimizer).
Or the logic would change and we would pass the model artifact in `model_name_or_path` and `resume_from_checkpoint` would become something like `optimizer_path` @pcuenca

**Comment by pcuenca** [comment]
I like the second solution better, the use of something like `optimizer_state_path` as you suggest is consistent with `model_name_or_path`.

If we were to adopt the first option, then the user could enter different references in `resume_from_checkpoint` and `model_name_or_path`, and we'd have to report an error in that case (or silently ignore the model).
