### ISSUE TITLE
Super curious if it is intentional to not include "CustomFlaxBartForConditionalGeneration" in the library?

### ISSUE THREAD

**Issue by ytsheng** [borisdayma/dalle-mini#129]
```
ImportError: cannot import name 'CustomFlaxBartForConditionalGeneration' from 'dalle_mini.model'
```

I could not find this module anywhere in the code. Let me know if this is intentional. :)

**Comment by ytsheng** [comment]
nvm, I found this: https://huggingface.co/spaces/flax-community/dalle-mini/blob/99a1ff5bc66b8a85a91e9505e2f61d8080dd7360/demo/CustomBARTv4b_model-generate.ipynb

Thanks.

**Comment by borisdayma** [comment]
Yeah the new version will use a different model
