### ISSUE TITLE
Checkpoint doesn't match

### ISSUE THREAD

**Issue by Sanqiang** [borisdayma/dalle-mini#131]
`self.model = DalleBart.from_pretrained("model", dtype=dtype, abstract_init=True)
`I got following error message for above line looks like the checkpoint doesn't match?
`ValueError: Trying to load the pretrained weight for ('model', 'decoder', 'embed_positions', 'embedding') failed: checkpoint has shape (257, 1024) which is incompatible with the model shape (256, 1024). Using `ignore_mismatched_sizes=True` if you really want to load this checkpoint inside this model.`

After updating to
`self.model = DalleBart.from_pretrained("model", dtype=dtype, abstract_init=True, ignore_mismatched_sizes=True)
`(add ignore_mismatched_sizes=True)
I got another error
TypeError: Value ShapeDtypeStruct(shape=(256, 1024), dtype=float32) with type <class 'jax._src.api.ShapeDtypeStruct'> is not a valid JAX type

Looks like both errors are from JAX, I install the latest JAX by `pip install jax[cuda11_cudnn805] -f `https://storage.googleapis.com/jax-releases/jax_releases.html

Any suggestions?

**Comment by borisdayma** [comment]
Sorry the repo is still unstable as I'm working towards scaling up the models.

I changed the model definition a few days ago so you may need to install from a previous commit.
The reason was the position tokens had an extra item that was not needed. Also having a multiple of 128 is more efficient on TPU's.

**Comment by interactivetech** [comment]
I was able to resolve the issue by changing the pip install of dalle-mini to: `pip install -q git+https://github.com/borisdayma/dalle-mini.git@14abe8c827eb85ee4081efe0749eba2a6ee9d8b4`

**Comment by borisdayma** [comment]
This should be now solved. Let me know if you still have any issue.

**Comment by shi3z** [comment]
Hi,It is really impressive work!
But I faced on similar problem in my local environment.
When it loading pre-trained model, then following error occurred. 

```
  File "/home/shi3z/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/transformers/models/bart/modeling_flax_bart.py", line 436, in __call__
    hidden_states = self.acticvation_dropout_layer(hidden_states, deterministic=deterministic)
AttributeError: "FlaxBartEncoderLayer" object has no attribute "acticvation_dropout_layer"

```

I tried previous repository too.
But it still happen.

Would you give me advice?

**Comment by borisdayma** [comment]
Did you try to update your installation?

**Comment by shi3z** [comment]
Awesome!

I updated transformers from 14.0 to 14.16, then it work well.
Thank you very much!
Best
