### ISSUE TITLE
Unicode-Decode-Error in "inference_pipeline.ipynb" at the processing-prompts step

### ISSUE THREAD

**Issue by illtellyoulater** [borisdayma/dalle-mini#146]
On Win 10 I'm running `inference_pipeline.ipynb` and when I get to _Our model requires processing prompts_, some files are downloaded and then I get the following error:

![dalle-mini-unicodedecode-error](https://user-images.githubusercontent.com/3078931/159835144-b2ccb2d0-4e4b-4dd1-9516-2995dadd3718.png)

The problem seems to happen when the program tries to decode this text file: https://huggingface.co/dalle-mini/dalle-mini/resolve/main/enwiki-words-frequency.txt.
If I open it with Visual Studio Code, I get a warning saying that the file contains many visually ambiguous (_confusables_) Unicode characters... anyway, without knowing too much about neural networks and about how DALLE works I would suspect there's a reason for them to be there...

So I would think the issue is more related to the transcoding between UTF-8 & Windows CP-1252... I had to do with something like that long time ago, and it still brings some painful memories... 😵😅

**Comment by illtellyoulater** [comment]
Ok I think I fixed it and it was less problematic than I thought... 
I just modified this line:

https://github.com/borisdayma/dalle-mini/blob/b7b619a2ab6b9dec1812d074fbee7b5abafae158/src/dalle_mini/model/text.py#L28

with:

`l.split()[0] for l in Path(wiki_word_frequency).read_text(encoding="utf8").splitlines()`

and it worked as expected.
Do you want me to make a PR?

**Comment by borisdayma** [comment]
This is great news! Yes a PR would be nice!
