### ISSUE TITLE
Can I download pre-trained models and generate images from Windows PC?

### ISSUE THREAD

**Issue by zydjohnHotmail** [borisdayma/dalle-mini#149]
Hello:
I didn’t have much experience with iPython Notebook.  I want to use the repo to generate some images from text prompt.
However, I read the notebook code from the file: tools/inference/inference_pipeline.ipynb.
I found that there are so many steps involved, it is many more steps than if I want to use the repo from huggingface web site, where I only need to type some text then press Enter key.
I want to know if I can download the pre-trained models (Dalle and VQGAN) and save in my local hard drive, then simply input some text, like “Flying pig” to generate some images, and also save in my local hard drive?
I mean I want to have one Python script, which can do the job as above, so I don’t have to go through all the steps in inference_pipeline.ipynb to generate images from text input.
Thanks,

**Comment by borisdayma** [comment]
You can now just use the demo: https://huggingface.co/spaces/dalle-mini/dalle-mini

**Comment by walking-octopus** [comment]
> You can now just use the demo: https://huggingface.co/spaces/dalle-mini/dalle-mini

It looks broken...
