### ISSUE TITLE
Backend URL

### ISSUE THREAD

**Issue by tom-doerr** [borisdayma/dalle-mini#169]
I would like to create [my own Hugging Spaces site](https://huggingface.co/spaces/tom-doerr/logo_generator), but getting a -5 Error since the `BACKEND_SERVER` URL is not set. Do I have to run my own backend server or is it possible to run this project completely on Hugging Faces?

**Comment by tom-doerr** [comment]
Probably not possible to run it on Hugging Spaces (issue https://github.com/borisdayma/dalle-mini/issues/163).

**Comment by borisdayma** [comment]
Yes that's correct.
We have only one app running at the moment but definitely want to improve the demo.
