### ISSUE TITLE
memory requirements

### ISSUE THREAD

**Issue by mhashas** [borisdayma/dalle-mini#185]
i am trying to run inference on a RTX 3080-TI, however I am getting RuntimeError: :0: cudaFuncSetAttribute(kernel_entry, cudaFuncAttributeMaxDynamicSharedMemorySize, integer_cast<int32_t>(launch_configs[0].smemSizeInBytes)): out of memory. 

I am not using the CLIP model. Am I doing something wrong or the model just does not fit on 12GB?

**Comment by borisdayma** [comment]
I think the model should fit as it works on Colab, do you run the inference notebook?

**Comment by pcuenca** [comment]
Hi @mhashas, I just tested the inference notebook on a 2080 Ti (11 GB of GPU RAM) and it works fine, at ~5s / image.

**Comment by mhashas** [comment]
I will close the issue then and reanalayze, I did transform the notebook in a python script so maybe some models / outputs are not cleared and kept in memory. Thank you for the response!

**Comment by mhashas** [comment]
For future reference, in case anyone encounters this, the solution for me was:

export XLA_PYTHON_CLIENT_MEM_FRACTION=0.8

You can paly with the fraction yourself.  For more info read: https://github.com/google/jax/issues/8506
