### ISSUE TITLE
Will dall-e mega be available through this repo?

### ISSUE THREAD

**Issue by LukeWood** [borisdayma/dalle-mini#186]
Hey Boris

I'm a huge fan of what you're doing.  making this sort of model available to everyone is a great thing.  will you be publishing the Dall-e mega weights when they're done training?

**Comment by borisdayma** [comment]
Yes, I'm already pushing the checkpoints while training.
If you open the demo colab referenced on the front page, you can see how to load it from wandb.

**Comment by LukeWood** [comment]
Thanks Boris!  Saw that after opening this and forgot to close.  Got it working, thanks!
