### ISSUE TITLE
Current Model Versions

### ISSUE THREAD

**Issue by melih1996** [borisdayma/dalle-mini#193]
Hello @borisdayma
Are the latest models like in the below?
{
  "mini"    :    "dalle-mini/dalle-mini/mini-1:v0",
  "mega"  :   "dalle-mini/dalle-mini/mega-1:latest"
}
For mini, I was getting worse results, that's why I needed to ask if the model used in hugging face is mini-1:v0 or not.
For mega, there are 2 versions I saw which are "mega-1:latest" and "mega-1-fp16:latest". Which one is the correct one?
Thank you.

**Comment by borisdayma** [comment]
That is correct, the demo uses "mega-1:latest".

"mega-1-fp16:latest" is for setups that don't have enough capacity.

**Comment by melih1996** [comment]
Thank you for the quick reply and this great work!
