### ISSUE TITLE
How to run the webapp locally

### ISSUE THREAD

**Issue by AetherUnbound** [borisdayma/dalle-mini#223]
Hi there! I'm interested in running the webapp locally. I've tried the following, but I end up with a `Service unavailable, status: 403` message. Do you know how I might be able to run this on my own machine?

I've added `.streamlit/secrets.toml` with the contents:

```toml
BACKEND_SERVER = "http://localhost:8502"
```

Then in one terminal I ran `streamlit run app/streamlit/backend.py` and in another I ran `streamlit run app/streamlit/app.py`. However as described, I get the error message above (and pictured below).

![Screenshot_2022-06-10_09-12-39](https://user-images.githubusercontent.com/10214785/173107947-38fae086-4c76-486b-a82a-5f980a5e48bc.png)

I'd be happy to contribute these instructions to the README.md once I get it up and running!

**Comment by borisdayma** [comment]
Look at the Dalle playground
