### ISSUE TITLE
Docker Image [dalle-backend] unrecognized arguments: 8080

### ISSUE THREAD

**Issue by Zeerti** [borisdayma/dalle-mini#252]
Trying to run the Docker image on Windows and I'm getting this error. I tried adjusting the Dockerfile in the backend folder from 
`CMD python3 app.py 8080` to `CMD python3 app.py --port 8080` but that didn't seem to make any difference.  Anyone have any suggestions? Getting the below error in an infinite loop. Front end starts up just fine though.

```
dalle-backend      | --> Starting DALL-E Server. This might take up to two minutes.
dalle-backend      | usage: app.py
dalle-backend      |        [-h]
dalle-backend      |        [--port PORT]
dalle-backend      |        [--model_version MODEL_VERSION]
dalle-backend      |        [--save_to_disk SAVE_TO_DISK]
dalle-backend      | app.py: error: unrecognized arguments: 8080
dalle-backend exited with code 2
```

**Comment by saharmor** [comment]
This issue should have been open in the [DALL-E Playground repository](https://github.com/saharmor/dalle-playground). Anyhow, this was fixed as part of a recent push. Please try again and open an issue in DALL-E Playground repo if the error persists.
