### ISSUE TITLE
ERROR: No matching distribution found for jaxlib==0.3.10+cuda11.cudnn82 (from jax[cuda])

### ISSUE THREAD

**Issue by Mshz2** [borisdayma/dalle-mini#267]
Hi, I am trying to build docker with the dockerfile that you provided in my azure virtual machine with below cuda details:
![image](https://user-images.githubusercontent.com/63469924/174452589-703d1d17-8871-4a17-85fb-8ea1240ecfd2.png)

![image](https://user-images.githubusercontent.com/63469924/174452608-3eb78d90-c99b-42ef-9d0f-732897a122b5.png)

**However, when I run the build docker I get error below**

![image](https://user-images.githubusercontent.com/63469924/174452530-0a710b85-208e-430d-8728-e16fdd9a4846.png)

**May I please ask if you have idea where the errors come from?**

**Comment by njoneja** [comment]
Same issue, building on WSL2 (20.04) or native Ubuntu 22.04

**Comment by cdgamedev** [comment]
Duplicate issue

#260
