### ISSUE TITLE
ERROR: Cannot install dalle-mini because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by mterczynski** [borisdayma/dalle-mini#268]
I get this error after running `pip install -e ".[dev]"` from readme:

```bash
Collecting black[jupyter]
  Downloading black-22.1.0-cp310-cp310-win_amd64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 3.6 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of dalle-mini[dev] to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install dalle-mini because these package versions have conflicting dependencies.

The conflict is caused by:
    optax 0.1.2 depends on jaxlib>=0.1.37
    optax 0.1.1 depends on jaxlib>=0.1.37
    optax 0.1.0 depends on jaxlib>=0.1.37
    optax 0.0.91 depends on jaxlib>=0.1.37
    optax 0.0.9 depends on jaxlib>=0.1.37
    optax 0.0.8 depends on jaxlib>=0.1.37
    optax 0.0.6 depends on jaxlib>=0.1.37
    optax 0.0.5 depends on jaxlib>=0.1.37
    optax 0.0.3 depends on jaxlib>=0.1.37
    optax 0.0.2 depends on jaxlib>=0.1.37
    optax 0.0.1 depends on jaxlib>=0.1.37

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts   
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.
```

Please note that I'm not a Python programmer so I apologize if this is something trivial. Any help would be welcome.

**Comment by jefedeoro** [comment]
Try 
'python.exe -m pip install --upgrade pip'

**Comment by laggron42** [comment]
Same here, upgrading to latest didn't fix

**Comment by mterczynski** [comment]
@jefedeoro I've upgraded pip to newest version, but unfortunately that didn't help with the main issue.

**Comment by borisdayma** [comment]
I don't think you need the dev dependencies if you just want to use the model.
The inference notebook will be a good place to start.

**Comment by cryptozealot** [comment]
```pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html```

**Comment by gordicaleksa** [comment]
Hitting this issue as well. What's the recommended way of training and most importantly debugging DALL-E mini on my local machine? Found some videos on how to run the inference script locally using Docker but would appreciate any advice when it comes to debugging/stepping through the code.

Additional context:
* My machine (laptop) specs: 16 GB RAM, RTX 2080 GPU, intel i9 CPU.
* I want to cover it in a YouTube video so I don't really need to train it per se - just be able to step through the code. So it can be a toy setup: minimal dataset (100 image-caption pairs works...), a minimal possible model that fits on my machine (I assume mini or smaller), etc. you hopefully get the point. :)
