### ISSUE TITLE
cannot import name 'OpShardingSharding' from 'jax.experimental.sharding'

### ISSUE THREAD

**Issue by ZaDonbass** [borisdayma/dalle-mini#305]
I successfully did "Installation and set-up" step  in "DALL·E mini - Inference pipeline", but when i try to import 

`from dalle_mini import DalleBart`

i got an error

`ImportError: cannot import name 'OpShardingSharding' from 'jax.experimental.sharding' (/usr/local/lib/python3.7/dist-packages/jax/experimental/sharding.py)`

what's the problem? what i did wrong?

**Comment by RubenGres** [comment]
I tried downgrading dalle-mini to 0.1.0 and it worked for me

**Comment by ZaDonbass** [comment]
> I tried downgrading dalle-mini to 0.1.0 and it worked for me `!pip install -q dalle-mini==0.1.0`

thanks!!! that helped me
