### ISSUE TITLE
A Question on The Carbon Footprint Estimation.

### ISSUE THREAD

**Issue by yaoyiran** [borisdayma/dalle-mini#318]
Hi,

The carbon emission is estimated in the [DALL-E Mega Model Card](https://huggingface.co/dalle-mini/dalle-mega) and [DALL-E Mini Model Card](https://huggingface.co/dalle-mini/dalle-mini) respectively. However, I have a concern about if the correct number of TPU-3 chips is fed to the [Machine Learning Emissions Calculator](https://mlco2.github.io/impact/#about).

DALL-E Mini: in the model card, the reported emission is 7.54 kg CO2-eq. It is trained on a single TPU v3-8 for 72 hours. However, I can find from [Google cloud's website](https://cloud.google.com/tpu/docs/system-architecture-tpu-vm) that a TPU v3-8 contains 8 tensorcores and 4 chips. So the input to the [Machine Learning Emissions Calculator](https://mlco2.github.io/impact/#about) should be 4 X 72 hours (rather than 72 hour which derives 7.54 kg CO2). So the emission should be 4 X 7.54 kg CO2-eq, in my opinion.

DALL-E Mega: in the model card, the reported emission is 4503 kg CO2-eq. It is trained on a TPU v3-256 for 1344 hours. However, I can find from [Google cloud's website](https://cloud.google.com/tpu/docs/system-architecture-tpu-vm) that a TPU v3-256 contains 256 tensorcores and 128 chips. So the input to the [Machine Learning Emissions Calculator](https://mlco2.github.io/impact/#about) should be 128 X 1344 hours (rather than 32 X 1344 hours which derives 4503 kg CO2). So the emission should be 4 X 4503 kg CO2-eq, in my opinion.

Could you double-check this a bit? Thank you so much!

**Comment by borisdayma** [comment]
Many thanks for noticing it.
I think that you are correct.
Do you want to do a pull request on the model cards?

**Comment by yaoyiran** [comment]
Thanks for your double-check! I just pulled requests for DALL-E Mega and DALL-E Mini respectively on their Hugginface model card pages.
