### ISSUE TITLE
Better defaults for model generation

### ISSUE THREAD

**Issue by borisdayma** [borisdayma/dalle-mini#57]
Model generation by default uses the parameters from Bart summarization model.
We should find good defaults and set them directly in the model config file.

**Comment by borisdayma** [comment]
This is now fixed

**Comment by patsybond172** [comment]
and how about Model generation by default uses the parameters from Bart summarization model? like this huh? [https://patsybond172.github.io/kitchen-cabinet](https://patsybond172.github.io/kitchen-cabinet)

**Comment by mayassuarez172** [comment]
> and how about Model generation by default uses the parameters from Bart summarization model? like this huh? https://patsybond172.github.io/kitchen-cabinet or this : https://github.com/patsybond172

yeah i think same with you

**Comment by mayassuarez172** [comment]
Good Idea's We should find good defaults and set them directly in the model config file.
[https://github.com/mayassuarez172](https://github.com/mayassuarez172)
[https://github.com/mayassuarez172/blue-kitchen-cabinets](https://github.com/mayassuarez172/blue-kitchen-cabinets)
[https://mayassuarez172.github.io/blue-kitchen-cabinets](https://mayassuarez172.github.io/blue-kitchen-cabinets)

**Comment by janicetyler** [comment]
> and how about Model generation by default uses the parameters from Bart summarization model? like this huh? https://patsybond172.github.io/kitchen-cabinet or this : https://github.com/patsybond172

i think i same with your opinion

**Comment by janicetyler** [comment]
Think different - Good Idea's We should find good defaults and set them directly in the model config file.
[https://github.com/janicetyler](https://github.com/janicetyler)
[https://github.com/janicetyler/wood-kitchen-cabinets](https://github.com/janicetyler/wood-kitchen-cabinets)
[https://janicetyler.github.io/wood-kitchen-cabinets](https://janicetyler.github.io/wood-kitchen-cabinets/)

**Comment by lucialam172** [comment]
> same with you

very interesting

**Comment by lucialam172** [comment]
Yeah I think We should find good defaults and set them directly in the model config file 
[https://github.com/lucialam172/dark-kitchen-cabinets](https://github.com/lucialam172/dark-kitchen-cabinets)
[https://github.com/lucialam172](https://github.com/lucialam172)
[https://lucialam172.github.io/dark-kitchen-cabinets](https://lucialam172.github.io/dark-kitchen-cabinets)
