### ISSUE TITLE
Datasets :)

### ISSUE THREAD

**Issue by christophschuhmann** [borisdayma/dalle-mini#6]
Hey guys!

I started the CRAWLING@HOME project. We are using CLIP to filter high quality image-text pairs from Common crawl. We already have almost 100M :)

Here is a preview:
http://gallerytest.christoph-schuhmann.de/photos/index.php?/category/4

Here is our current progress bar:
http://cah.io.community/?all=true

We still need to do a deduplication, after that ~25% will remain. We already did an analysis on that and recently began to dedupe while crawling.

I can give you a DL link if interested :)

Feel free to join the discord server we're active on in the #datasets channel:
https://discord.gg/Za3URNVwGF

**Comment by christophschuhmann** [comment]
Here is also a dataset i stumbled over: 
80+M of stock photo previews without watermarks from the stock photo page alamy: 
https://the-eye.eu/eleuther_staging/Alamy/ 
:)

**Comment by borisdayma** [comment]
This is awesome!
You should look into adding it to the huggingface dataset hub if it's possible so anybody can use them easily!

**Comment by christophschuhmann** [comment]
The Alamy is some kind of a legal grey zone :) 

But CRAWLING@HOME can definetily become one :)

**Comment by christophschuhmann** [comment]
More data:
https://github.com/christophschuhmann/4MC-4M-Image-Text-Pairs-with-CLIP-embeddings

**Comment by christophschuhmann** [comment]
More :) 

![image](https://user-images.githubusercontent.com/22318853/125861813-30acddbb-d898-4b9d-9625-9ea5bc197c8c.png)


https://drive.google.com/file/d/1-5O7976oAnFl3zCLyU7e9qm2lxIOTCn0/view?usp=sharing

**Comment by borisdayma** [comment]
Very cool!
We'll need to gather all the data for a future run!
Now we're just prototyping but it's looking good!

**Comment by borisdayma** [comment]
Closing this issue, there's now plenty of data to use with LAION
