### ISSUE TITLE
Improving DALL·E mini.

### ISSUE THREAD

**Issue by Gertie01** [borisdayma/dalle-mini#94]
st.columns has graduated out of beta. On 2021-11-02, the beta_ version will be removed.

Before then, update your code from st.beta_columns to st.columns please.

**Comment by pcuenca** [comment]
Our demo app is intended for a huggingface Space environment, and we don't control the version of streamlit that runs there. We'll verify if `st.columns` is available and will update the name if possible. Thanks!

**Comment by borisdayma** [comment]
We actually already merged this change and it worked fine
